GotoUI1740063269 = {};
GotoUI1740063269["1"] = Instance.new("ScreenGui", game:GetService("CoreGui").RobloxGui);
GotoUI1740063269["1"]["Name"] = [[GotoUI]];
GotoUI1740063269["1"]["IgnoreGuiInset"] = true
GotoUI1740063269["1"]["DisplayOrder"] = 2147483647
GotoUI1740063269["1"]["ZIndexBehavior"] = Enum.ZIndexBehavior.Sibling;
GotoUI1740063269["2"] = Instance.new("Frame", GotoUI1740063269["1"]);
GotoUI1740063269["2"]["BorderSizePixel"] = 0;
GotoUI1740063269["2"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
GotoUI1740063269["2"]["AnchorPoint"] = Vector2.new(0.5, 0.5);
GotoUI1740063269["2"]["Size"] = UDim2.new(0.18677, 0, 0.13201, 0);
GotoUI1740063269["2"]["Position"] = UDim2.new(0.115, 0, 0.915, 0);
GotoUI1740063269["2"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
GotoUI1740063269["2"]["Name"] = [[GotoFrame]];
GotoUI1740063269["3"] = Instance.new("UICorner", GotoUI1740063269["2"]);
GotoUI1740063269["3"]["Name"] = [[Corner]];
GotoUI1740063269["3"]["CornerRadius"] = UDim.new(0, 14);
GotoUI1740063269["4"] = Instance.new("TextLabel", GotoUI1740063269["2"]);
GotoUI1740063269["4"]["TextWrapped"] = true;
GotoUI1740063269["4"]["BorderSizePixel"] = 0;
GotoUI1740063269["4"]["TextSize"] = 14;
GotoUI1740063269["4"]["TextXAlignment"] = Enum.TextXAlignment.Left;
GotoUI1740063269["4"]["TextScaled"] = true;
GotoUI1740063269["4"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
GotoUI1740063269["4"]["FontFace"] = Font.new([[rbxasset://fonts/families/GothamSSm.json]], Enum.FontWeight.SemiBold, Enum.FontStyle.Normal);
GotoUI1740063269["4"]["TextColor3"] = Color3.fromRGB(31, 31, 31);
GotoUI1740063269["4"]["BackgroundTransparency"] = 1;
GotoUI1740063269["4"]["Size"] = UDim2.new(0.7895, 0, 0.19266, 0);
GotoUI1740063269["4"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
GotoUI1740063269["4"]["Text"] = [[GoTo]];
GotoUI1740063269["4"]["Name"] = [[Title]];
GotoUI1740063269["4"]["Position"] = UDim2.new(0.02874, 0, 0, 0);
GotoUI1740063269["5"] = Instance.new("TextBox", GotoUI1740063269["2"]);
GotoUI1740063269["5"]["CursorPosition"] = -1;
GotoUI1740063269["5"]["Name"] = [[NameBox]];
GotoUI1740063269["5"]["PlaceholderColor3"] = Color3.fromRGB(6, 6, 6);
GotoUI1740063269["5"]["BorderSizePixel"] = 0;
GotoUI1740063269["5"]["TextSize"] = 14;
GotoUI1740063269["5"]["TextColor3"] = Color3.fromRGB(6, 6, 6);
GotoUI1740063269["5"]["BackgroundColor3"] = Color3.fromRGB(241, 241, 241);
GotoUI1740063269["5"]["FontFace"] = Font.new([[rbxasset://fonts/families/GothamSSm.json]], Enum.FontWeight.Medium, Enum.FontStyle.Normal);
GotoUI1740063269["5"]["ClearTextOnFocus"] = false;
GotoUI1740063269["5"]["PlaceholderText"] = [[Player Name]];
GotoUI1740063269["5"]["Size"] = UDim2.new(0.83231, 0, 0.40867, 0);
GotoUI1740063269["5"]["Position"] = UDim2.new(0.0838, 0, 0.18361, 0);
GotoUI1740063269["5"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
GotoUI1740063269["5"]["Text"] = [[]];
GotoUI1740063269["6"] = Instance.new("UICorner", GotoUI1740063269["5"]);
GotoUI1740063269["6"]["Name"] = [[Corner]];
GotoUI1740063269["6"]["CornerRadius"] = UDim.new(0, 15);
GotoUI1740063269["7"] = Instance.new("TextButton", GotoUI1740063269["2"]);
GotoUI1740063269["7"]["TextWrapped"] = true;
GotoUI1740063269["7"]["BorderSizePixel"] = 0;
GotoUI1740063269["7"]["TextColor3"] = Color3.fromRGB(6, 6, 6);
GotoUI1740063269["7"]["AutoButtonColor"] = false;
GotoUI1740063269["7"]["TextSize"] = 14;
GotoUI1740063269["7"]["TextScaled"] = true;
GotoUI1740063269["7"]["BackgroundColor3"] = Color3.fromRGB(241, 241, 241);
GotoUI1740063269["7"]["FontFace"] = Font.new([[rbxasset://fonts/families/GothamSSm.json]], Enum.FontWeight.Medium, Enum.FontStyle.Normal);
GotoUI1740063269["7"]["Size"] = UDim2.new(0.27997, 0, 0.23418, 0);
GotoUI1740063269["7"]["Name"] = [[Button]];
GotoUI1740063269["7"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
GotoUI1740063269["7"]["Text"] = [[Goto]];
GotoUI1740063269["7"]["Position"] = UDim2.new(0.35652, 0, 0.67703, 0);
GotoUI1740063269["8"] = Instance.new("UICorner", GotoUI1740063269["7"]);
GotoUI1740063269["8"]["Name"] = [[Corner]];
GotoUI1740063269["8"]["CornerRadius"] = UDim.new(0, 10);
GotoUI1740063269["9"] = Instance.new("TextButton", GotoUI1740063269["2"]);
GotoUI1740063269["9"]["TextWrapped"] = true;
GotoUI1740063269["9"]["BorderSizePixel"] = 0;
GotoUI1740063269["9"]["TextColor3"] = Color3.fromRGB(6, 6, 6);
GotoUI1740063269["9"]["AutoButtonColor"] = false;
GotoUI1740063269["9"]["TextSize"] = 14;
GotoUI1740063269["9"]["TextScaled"] = true;
GotoUI1740063269["9"]["BackgroundColor3"] = Color3.fromRGB(241, 241, 241);
GotoUI1740063269["9"]["FontFace"] = Font.new([[rbxasset://fonts/families/GothamSSm.json]], Enum.FontWeight.Medium, Enum.FontStyle.Normal);
GotoUI1740063269["9"]["Size"] = UDim2.new(0.08039, 0, 0.23418, 0);
GotoUI1740063269["9"]["Name"] = [[Close]];
GotoUI1740063269["9"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
GotoUI1740063269["9"]["Text"] = [[X]];
GotoUI1740063269["9"]["Position"] = UDim2.new(0.915, 0, 0.025, 0);
GotoUI1740063269["a"] = Instance.new("UICorner", GotoUI1740063269["9"]);
GotoUI1740063269["a"]["Name"] = [[Corner]];
GotoUI1740063269["a"]["CornerRadius"] = UDim.new(0, 10);
GotoUI1740063269["b"] = Instance.new("UIAspectRatioConstraint", GotoUI1740063269["9"]);
GotoUI1740063269["b"]["Name"] = [[Aspect]];
GotoUI1740063269["c"] = Instance.new("Frame", GotoUI1740063269["2"]);
GotoUI1740063269["c"]["Visible"] = false;
GotoUI1740063269["c"]["ZIndex"] = 10;
GotoUI1740063269["c"]["BorderSizePixel"] = 0;
GotoUI1740063269["c"]["BackgroundColor3"] = Color3.fromRGB(0, 0, 0);
GotoUI1740063269["c"]["Size"] = UDim2.new(1, 0, 1, 0);
GotoUI1740063269["c"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
GotoUI1740063269["c"]["Name"] = [[CloseFrame]];
GotoUI1740063269["c"]["BackgroundTransparency"] = 0.3;
GotoUI1740063269["d"] = Instance.new("UICorner", GotoUI1740063269["c"]);
GotoUI1740063269["d"]["Name"] = [[Corner]];
GotoUI1740063269["d"]["CornerRadius"] = UDim.new(0, 14);
GotoUI1740063269["e"] = Instance.new("TextLabel", GotoUI1740063269["c"]);
GotoUI1740063269["e"]["TextWrapped"] = true;
GotoUI1740063269["e"]["BorderSizePixel"] = 0;
GotoUI1740063269["e"]["TextSize"] = 14;
GotoUI1740063269["e"]["TextScaled"] = true;
GotoUI1740063269["e"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
GotoUI1740063269["e"]["FontFace"] = Font.new([[rbxasset://fonts/families/GothamSSm.json]], Enum.FontWeight.SemiBold, Enum.FontStyle.Normal);
GotoUI1740063269["e"]["TextColor3"] = Color3.fromRGB(255, 255, 255);
GotoUI1740063269["e"]["BackgroundTransparency"] = 1;
GotoUI1740063269["e"]["Size"] = UDim2.new(0.74135, 0, 0.25918, 0);
GotoUI1740063269["e"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
GotoUI1740063269["e"]["Text"] = [[Are you sure?]];
GotoUI1740063269["e"]["Name"] = [[Title]];
GotoUI1740063269["e"]["Position"] = UDim2.new(0.12312, 0, 0.11099, 0);
GotoUI1740063269["f"] = Instance.new("TextLabel", GotoUI1740063269["c"]);
GotoUI1740063269["f"]["TextWrapped"] = true;
GotoUI1740063269["f"]["BorderSizePixel"] = 0;
GotoUI1740063269["f"]["TextSize"] = 14;
GotoUI1740063269["f"]["TextScaled"] = true;
GotoUI1740063269["f"]["BackgroundColor3"] = Color3.fromRGB(255, 255, 255);
GotoUI1740063269["f"]["FontFace"] = Font.new([[rbxasset://fonts/families/GothamSSm.json]], Enum.FontWeight.SemiBold, Enum.FontStyle.Normal);
GotoUI1740063269["f"]["TextColor3"] = Color3.fromRGB(241, 241, 241);
GotoUI1740063269["f"]["BackgroundTransparency"] = 1;
GotoUI1740063269["f"]["Size"] = UDim2.new(0.74135, 0, 0.25918, 0);
GotoUI1740063269["f"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
GotoUI1740063269["f"]["Text"] = [[You can open gui with press Ctrl+X]];
GotoUI1740063269["f"]["Name"] = [[Subtitle]];
GotoUI1740063269["f"]["Position"] = UDim2.new(0.12312, 0, 0.33296, 0);
GotoUI1740063269["10"] = Instance.new("TextButton", GotoUI1740063269["c"]);
GotoUI1740063269["10"]["TextWrapped"] = true;
GotoUI1740063269["10"]["BorderSizePixel"] = 0;
GotoUI1740063269["10"]["TextColor3"] = Color3.fromRGB(6, 6, 6);
GotoUI1740063269["10"]["AutoButtonColor"] = false;
GotoUI1740063269["10"]["TextSize"] = 14;
GotoUI1740063269["10"]["TextScaled"] = true;
GotoUI1740063269["10"]["BackgroundColor3"] = Color3.fromRGB(241, 241, 241);
GotoUI1740063269["10"]["FontFace"] = Font.new([[rbxasset://fonts/families/GothamSSm.json]], Enum.FontWeight.Medium, Enum.FontStyle.Normal);
GotoUI1740063269["10"]["Size"] = UDim2.new(0.34988, 0, 0.31893, 0);
GotoUI1740063269["10"]["Name"] = [[Yes]];
GotoUI1740063269["10"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
GotoUI1740063269["10"]["Text"] = [[Yes, close]];
GotoUI1740063269["10"]["Position"] = UDim2.new(0.07636, 0, 0.62558, 0);
GotoUI1740063269["11"] = Instance.new("UICorner", GotoUI1740063269["10"]);
GotoUI1740063269["11"]["Name"] = [[Corner]];
GotoUI1740063269["11"]["CornerRadius"] = UDim.new(0, 10);
GotoUI1740063269["12"] = Instance.new("TextButton", GotoUI1740063269["c"]);
GotoUI1740063269["12"]["TextWrapped"] = true;
GotoUI1740063269["12"]["BorderSizePixel"] = 0;
GotoUI1740063269["12"]["TextColor3"] = Color3.fromRGB(6, 6, 6);
GotoUI1740063269["12"]["AutoButtonColor"] = false;
GotoUI1740063269["12"]["TextSize"] = 14;
GotoUI1740063269["12"]["TextScaled"] = true;
GotoUI1740063269["12"]["BackgroundColor3"] = Color3.fromRGB(241, 241, 241);
GotoUI1740063269["12"]["FontFace"] = Font.new([[rbxasset://fonts/families/GothamSSm.json]], Enum.FontWeight.Medium, Enum.FontStyle.Normal);
GotoUI1740063269["12"]["Size"] = UDim2.new(0.34988, 0, 0.31893, 0);
GotoUI1740063269["12"]["Name"] = [[No]];
GotoUI1740063269["12"]["BorderColor3"] = Color3.fromRGB(0, 0, 0);
GotoUI1740063269["12"]["Text"] = [[No, back]];
GotoUI1740063269["12"]["Position"] = UDim2.new(0.51381, 0, 0.62558, 0);
GotoUI1740063269["13"] = Instance.new("UICorner", GotoUI1740063269["12"]);
GotoUI1740063269["13"]["Name"] = [[Corner]];
GotoUI1740063269["13"]["CornerRadius"] = UDim.new(0, 10);
GotoUI1740063269["14"] = Instance.new("UIAspectRatioConstraint", GotoUI1740063269["2"]);
GotoUI1740063269["14"]["AspectRatio"] = 2.5;
GotoUI1740063269["15"] = Instance.new("LocalScript", GotoUI1740063269["1"]);
GotoUI1740063269["15"]["Name"] = [[Code]];
local Code = function()
	local script = GotoUI1740063269["15"];
	local Main = (script.Parent.GotoFrame)
	local Speed = 0.1
	local TweenInfo = TweenInfo.new(Speed)
	local LocalPlayer = game:GetService("Players").LocalPlayer
	local UserInputService = game:GetService("UserInputService")

	local FindPlayer = function(input)
		for _, V1 in pairs(game:GetService("Players"):GetPlayers()) do
			if input:lower() == V1.Name:lower():sub(1, #input) then
				return V1;
			end
		end
	end

	Main.Button.MouseButton1Click:Connect(function()
		local Target = FindPlayer(Main.NameBox.Text)
		if Target ~= nil and Target:IsA("Player") then
			LocalPlayer.Character:SetPrimaryPartCFrame(CFrame.new(Target.Character.PrimaryPart.Position + (Target.Character.PrimaryPart.CFrame.LookVector * 4), Target.Character.PrimaryPart.Position))
		end
	end)

	local function ToggleClose()
		Main.CloseFrame.Visible = true
		game:GetService("TweenService"):Create(Main.CloseFrame, TweenInfo, {BackgroundTransparency = 0.3}):Play()
		for _, V1 in pairs(Main.CloseFrame:GetChildren()) do
			if V1:IsA("TextButton") then
				game:GetService("TweenService"):Create(V1, TweenInfo, {BackgroundTransparency = 0}):Play()
				game:GetService("TweenService"):Create(V1, TweenInfo, {TextTransparency = 0}):Play()
			elseif V1:IsA("TextLabel") then
				game:GetService("TweenService"):Create(V1, TweenInfo, {TextTransparency = 0}):Play()
			end
		end

		Main.CloseFrame.Yes.MouseButton1Click:Connect(function()
			game:GetService("TweenService"):Create(Main, TweenInfo, {BackgroundTransparency = 1}):Play()
			game:GetService("TweenService"):Create(Main, TweenInfo, {Position = Main.Position+UDim2.new(0,0,0.02,0)}):Play()
			game:GetService("TweenService"):Create(Main.CloseFrame, TweenInfo, {BackgroundTransparency = 1}):Play()
			for _, V1 in pairs(Main.CloseFrame:GetChildren()) do
				if V1:IsA("TextButton") then
					game:GetService("TweenService"):Create(V1, TweenInfo, {BackgroundTransparency = 1}):Play()
					game:GetService("TweenService"):Create(V1, TweenInfo, {TextTransparency = 1}):Play()
				elseif V1:IsA("TextLabel") then
					game:GetService("TweenService"):Create(V1, TweenInfo, {TextTransparency = 1}):Play()
				end
			end
			for _, V1 in pairs(Main:GetChildren()) do
				if V1:IsA("TextButton") or V1:IsA("TextBox") then
					game:GetService("TweenService"):Create(V1, TweenInfo, {BackgroundTransparency = 1}):Play()
					game:GetService("TweenService"):Create(V1, TweenInfo, {TextTransparency = 1}):Play()
				elseif V1:IsA("TextLabel") then
					game:GetService("TweenService"):Create(V1, TweenInfo, {TextTransparency = 1}):Play()
				end
			end
			wait(Speed)
			Main.Visible = false
		end)

		Main.CloseFrame.No.MouseButton1Click:Connect(function()
			game:GetService("TweenService"):Create(Main.CloseFrame, TweenInfo, {BackgroundTransparency = 1}):Play()
			for _, V1 in pairs(Main.CloseFrame:GetChildren()) do
				if V1:IsA("TextLabel") or V1:IsA("TextButton") then
					game:GetService("TweenService"):Create(V1, TweenInfo, {BackgroundTransparency = 1}):Play()
					game:GetService("TweenService"):Create(V1, TweenInfo, {TextTransparency = 1}):Play()
				end
			end
			wait(Speed)
			Main.CloseFrame.Visible = false
		end)
	end

	local function ToggleOpen()
		Main.Visible = true
		game:GetService("TweenService"):Create(Main, TweenInfo, {BackgroundTransparency = 0}):Play()
		game:GetService("TweenService"):Create(Main, TweenInfo, {Position = Main.Position-UDim2.new(0,0,0.02,0)}):Play()
		for _, V1 in pairs(Main:GetChildren()) do
			if V1:IsA("TextButton") or V1:IsA("TextBox") then
				game:GetService("TweenService"):Create(V1, TweenInfo, {BackgroundTransparency = 0}):Play()
				game:GetService("TweenService"):Create(V1, TweenInfo, {TextTransparency = 0}):Play()
			elseif V1:IsA("TextLabel") then
				game:GetService("TweenService"):Create(V1, TweenInfo, {TextTransparency = 0}):Play()
			end
		end
	end

	Main.Close.MouseButton1Click:Connect(function()
		ToggleClose()
	end)

	UserInputService.InputBegan:Connect(function(input, gameProcessed)
		if not gameProcessed then
			if input.KeyCode == Enum.KeyCode.X and UserInputService:IsKeyDown(Enum.KeyCode.LeftControl) then
				if Main.Visible == true then
					ToggleClose()
				elseif Main.Visible == false then
					ToggleOpen()
				end
			end
		end
	end)
end;
local Dragify = function()
	local script = GotoUI1740063269["15"];
	local UIS = game:GetService("UserInputService")
	local Frame = script.Parent.GotoFrame
	local dragToggle = nil
	local dragSpeed = 0.75
	local easingStyle = Enum.EasingStyle.Quint
	local easingDirection = Enum.EasingDirection.Out
	local dragInput = nil
	local dragStart = nil
	local startPos = nil
	local dragPos = nil
	Frame.InputBegan:Connect(function(input)
		if (input.UserInputType == Enum.UserInputType.MouseButton1 or input.UserInputType == Enum.UserInputType.Touch) and UIS:GetFocusedTextBox() == nil then
			dragToggle = true
			dragStart = input.Position
			startPos = Frame.Position
			input.Changed:Connect(function()
				if input.UserInputState == Enum.UserInputState.End then
					dragToggle = false
				end
			end)
		end
	end)
	Frame.InputChanged:Connect(function(input)
		if input.UserInputType == Enum.UserInputType.MouseMovement or input.UserInputType == Enum.UserInputType.Touch then
			dragInput = input
		end
	end)
	UIS.InputChanged:Connect(function(input)
		if input == dragInput and dragToggle then
			local Delta = input.Position - dragStart
			local Position = UDim2.new(startPos.X.Scale, startPos.X.Offset + Delta.X, startPos.Y.Scale, startPos.Y.Offset + Delta.Y)
			game:GetService("TweenService"):Create(Frame, TweenInfo.new(dragSpeed,easingStyle,easingDirection), {Position = Position}):Play()
		end
	end)
end
task.spawn(Code);
task.spawn(Dragify);
return GotoUI1740063269["1"];
